@Ambev.DeveloperEvaluation.WebApi_HostAddress = http://localhost:5119
@SaleId = ac450ca4-feec-4cc0-9afa-1b178cd5a365

### Create sale
POST {{Ambev.DeveloperEvaluation.WebApi_HostAddress}}/api/sales
Content-Type: application/json
Accept: application/json
{
  "number": 1,
  "customerName": "Customer Name",
  "date": "2026-08-04T02:40:07.148Z",
  "branch": "Store X",
  "status": 0,
  "products": [
    {
      "productId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "quantity": 2,
      "unitPrice": 10
    }
  ]
}

### Update sale
PUT {{Ambev.DeveloperEvaluation.WebApi_HostAddress}}/api/sales/{{SaleId}}
Content-Type: application/json
Accept: application/json
{
  "number": 2,
  "customerName": "Customer Name",
  "date": "2026-08-04T02:40:07.148Z",
  "branch": "Store X",
  "status": 3,
  "products": [
    {
      "productId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "quantity": 12,
      "unitPrice": 10
    },
    {
      "productId": "3fa85f64-5717-4562-b3fc-2c963f66afa7",
      "quantity": 2,
      "unitPrice": 10
    }
  ]
}

### Get sale
GET {{Ambev.DeveloperEvaluation.WebApi_HostAddress}}/api/sales/{{SaleId}}
Accept: application/json
